# Stage 0, "build-stage", based on Node.js, to build and compile the frontend
FROM tiangolo/node-frontend:10

WORKDIR /app

COPY package*.json /app/

RUN npm install -g npm@6.9
RUN npm install

COPY ./ /app/

ARG FRONTEND_ENV=dev

ENV VUE_APP_ENV=${FRONTEND_ENV}



