default_context:
  project_name: 'journapp'
  project_slug: 'journapp'
  domain_main: 'journapp.com'
  domain_staging: 'stag.journapp.com'
  docker_swarm_stack_name_main: 'journapp-com'
  docker_swarm_stack_name_staging: 'stag-journapp-com'
  secret_key: '5a727f732bd07222328997b9c93adc05f90a166429e12e577e3cc4919b47851a'
  first_superuser: 'matplinta@gmail.com'
  first_superuser_password: 'admin'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.journapp.com", "https://stag.journapp.com", "https://journapp.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@journapp.com'
  postgres_password: 'postgres'
  pgadmin_default_user: 'matplinta@gmail.com'
  pgadmin_default_user_password: 'admin'
  traefik_constraint_tag: 'journapp.com'
  traefik_constraint_tag_staging: 'stag.journapp.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:admin'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
